files:
  - source: /*.md
    translation: /%two_letters_code%/%original_file_name%
    ignore:
      - '/_coverpage.md'
      - '/_navbar.md'

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
