name: Deploy Github Pages

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'pr-2316'

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  deploy-gh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Option1: Copy /lib flow
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 18
      #     cache: 'npm'
      # - name: install dependencies
      #   run: npm ci --ignore-scripts

      # - name: build project
      #   run: npm run build

      # - name: rewrite .gitignore to include /lib files
      #   run: sed -i '/lib/d' .gitignore

      # - name: add /lib files
      #   run: git add ./lib

      # Option2: rewrite path
      - name: Rewirte docsify.js to import docsify.min.js
        run: sed -i 's|\"\/lib\/docsify.js|\"\/lib\/docsify.min.js|g' ./docs/index.html

      - name: Rewirte all local path to CDN @4
        run: sed -i 's|\"\/lib|\"\/\/cdn.jsdelivr.net\/npm\/docsify@4\/lib|g' ./docs/index.html

      - name: View rewirted index.html
        run: cat ./docs/index.html

      - name: Deploy to GithubPages
        uses: peaceiris/actions-gh-pages@v3
        #if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          enable_jekyll: true
          keep_files: true
          force_orphan: true
          allow_empty_commit: true
          commit_message: ${{ github.event.head_commit.message }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
