name: Deploy Github Page

on:
  push:
    branches:
      - 'main'
      - 'pr-2316'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Build Lib
        run: npm run build
      - name: Add Changes of Lib
        run: git add ./lib -f
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        #if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          enable_jekyll: true
          keep_files: true
          force_orphan: true
