name: Generate Sitemap

on:
  push:
    paths:
      - 'docs/**'     
  workflow_dispatch: {} 
  schedule:
    - cron: '0 0 * * *' 

jobs:
  sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Generate Sitemap XML
        run: node scripts/generateSitemap.js

      - name: Commit and push sitemap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update sitemap.xml"
          branch: sitemap
